version: '3.5'

services:
  etcd:
    container_name: milvus-etcd
    image: quay.io/coreos/etcd:v3.5.5
    environment:
      - ETCD_AUTO_COMPACTION_MODE=revision
      - ETCD_AUTO_COMPACTION_RETENTION=1000
      - ETCD_QUOTA_BACKEND_BYTES=4294967296
      - ETCD_SNAPSHOT_COUNT=50000
    volumes:
      - ${DOCKER_VOLUME_DIRECTORY:-.}/volumes/etcd:/etcd
    command: etcd -advertise-client-urls=http://127.0.0.1:2379 -listen-client-urls http://0.0.0.0:2379 --data-dir /etcd
    healthcheck:
      test: ["CMD", "etcdctl", "endpoint", "health"]
      interval: 30s
      timeout: 20s
      retries: 3

  milvus-minio:
    image: minio/minio:latest
    container_name: milvus-minio
    command: server /data
    environment:
      MINIO_ROOT_USER: "minioadmin"
      MINIO_ROOT_PASSWORD: "minioadmin"
    ports:
      - "9000:9000"
    volumes:
      - milvus_minio_data:/data

  standalone:
    container_name: milvus-standalone
    image: milvusdb/milvus:v2.4.4-20240531-8e7f36d9-arm64
    platform: linux/arm64
    command: ["milvus", "run", "standalone"]
    environment:
      ETCD_ENDPOINTS: etcd:2379
      MINIO_ADDRESS: milvus-minio:9000
      DATA_COORD__COMPACTION__ENABLE: false
    volumes:
      - ${DOCKER_VOLUME_DIRECTORY:-.}/volumes/milvus:/var/lib/milvus
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9091/healthz"]
      interval: 30s
      start_period: 90s
      timeout: 20s
      retries: 3
    ports:
      - "19530:19530"
      - "9091:9091"
    depends_on:
      - "etcd"
      - "milvus-minio"

  migration-agent:
    image: registry.zilliz.com/zilliz/migration-agent:latest
    container_name: migration-agent
    environment:
      - MILVUS_ENDPOINT=standalone:19530
      - MILVUS_USER=test
      - MILVUS_PASSWORD=1234
    ports:
      - "3333:3333"
    depends_on:
      - standalone

networks:
  default:
    name: milvus

volumes:
  milvus_minio_data:
